[package]
name = "philips-sys"
edition = "2021"
version = "0.1.0"
authors = ["AzHicham <hicham.azimani1@gmail.com>"]
description = "Rust bindings of Philips Open Pathology C++ library"
readme = "README.md"
keywords = ["philips", "isyntax", "histopathology", "microscopy"]
categories = ["science"]
license = "MIT/Apache-2.0"

[dependencies]
thiserror = "1.0"
autocxx = "0.23.1"
cxx = "1.0"

[build-dependencies]
cxx-build = "1.0"
autocxx-build = "0.23.1"
miette = { version = "5", features = ["fancy"] } # optional but gives nicer error messages!

[dev-dependencies]
rstest = "0.15"
assert_approx_eq = "1.1"
bencher = "0.1"
