[package]
name = "philips-isyntax-rs"
edition = "2021"
version = "0.1.0"
authors = ["AzHicham <hicham.azimani1@gmail.com>"]
description = "Rust bindings of Philips Open Pathology C++ library"
readme = "README.md"
keywords = ["philips", "isyntax", "histopathology", "microscopy"]
categories = ["science"]
license = "MIT/Apache-2.0"

[features]
default = ["image"]
image = ["dep:image"]

[dependencies]
thiserror = "1.0"
cxx = "1.0"
image = { version = "0.24", optional = true, default-features = false}

[build-dependencies]
cxx-build = "1.0"
miette = { version = "5", features = ["fancy"] } # optional but gives nicer error messages!

[dev-dependencies]
rstest = "0.15"
bencher = "0.1"
