name: Benchmarks

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

env:
  CARGO_TERM_COLOR: always
  RUST_VERSION: 1.75.0

jobs:
  benchmarks:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4 # v4
    - name: Cache sample slide
      id: cache-slide
      uses: actions/cache@v4
      with:
        path: tests/data/
        key: slides-test
    - name: Cache SDK
      id: cache-sdk
      uses: actions/cache@v4
      with:
        path: /tmp/sdk/
        key: cache-sdk
    - name: Google Storage authentication
      if: ${{ steps.cache-slide.outputs.cache-hit != 'true' || steps.cache-sdk.outputs.cache-hit != 'true' }}
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
        export_environment_variables: true
        create_credentials_file: true
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      if: ${{ steps.cache-slide.outputs.cache-hit != 'true' || steps.cache-sdk.outputs.cache-hit != 'true' }}
    - name: Download sample tests data
      if: steps.cache-slide.outputs.cache-hit != 'true'
      run: make dl-test-images
    - name: Download dependencies
      if: steps.cache-sdk.outputs.cache-hit != 'true'
      run: make dl-sdk
    - name: Install dependencies
      run: make install-deps
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ env.RUST_VERSION }}
    - uses: Swatinem/rust-cache@v2
      with:
        key: ubuntu-benchmark
    - name: Run cargo bench
      run: cargo bench --workspace | tee bench-output.txt
    - name: Store benchmark result
      uses: rhysd/github-action-benchmark@v1
      with:
        name: philips-isyntax-rs Benchmark
        tool: 'cargo'
        save-data-file: ${{ github.event_name == 'push' }}
        output-file-path: bench-output.txt
        benchmark-data-dir-path: '.'
        max-items-in-chart: 30
        github-token: ${{ secrets.GITHUB_TOKEN }}
        auto-push: ${{ github.event_name == 'push' }}
        alert-threshold: '120%'
        comment-on-alert: true
        fail-on-alert: true
        comment-always: true
        alert-comment-cc-users: '@AzHicham'
