name: Benchmarks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  benchmarks:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Google Storage authentication
      uses: google-github-actions/auth@v0
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
        export_environment_variables: true
        create_credentials_file: true
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
    - name: Install dependencies
      run: make install-deps
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - uses: Swatinem/rust-cache@v2
      with:
        key: ubuntu-benchmark
    - name: Run cargo bench
      run: cargo bench --workspace | tee bench-output.txt
    - name: Store benchmark result
      uses: rhysd/github-action-benchmark@v1.15.0
      with:
        name: philips-isyntax-rs Benchmark
        tool: 'cargo'
        save-data-file: ${{ github.event_name == 'push' }}
        output-file-path: bench-output.txt
        benchmark-data-dir-path: '.'
        max-items-in-chart: 30
        github-token: ${{ secrets.GITHUB_TOKEN }}
        auto-push: true
        alert-threshold: '200%'
        comment-on-alert: true
        fail-on-alert: true
        comment-always: true
        alert-comment-cc-users: '@AzHicham'
