name: Clippy checks

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Google Storage authentication
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
        export_environment_variables: true
        create_credentials_file: true
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
    - name: Install dependencies
      run: make install-deps
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: rustfmt, clippy
    - name: Run cargo clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --all --fix --all-targets --allow-dirty
    - name: Run cargo fmt
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all
    - name: Run cargo check
      uses: actions-rs/cargo@v1
      with:
        command: check
        args: --workspace --verbose
    - name: Commit and push changes
      continue-on-error: true
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.SCOPED_GITHUB_TOKEN }}
        commit-message: Run clippy on the code base
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        title: '[Clippy] Code maintenance'
        body: |
          🤖 This is an automatic PR 🤖
          Clippy suggests the following changes
        labels: not_in_changelog
        branch: auto/clippy
        base: main
    - name: Check outputs
      if: ${{ success() }}
      run: |
        echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"
        echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
