name: Coverage

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUST_VERSION: 1.72.1

jobs:
  coverage:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: Google Storage authentication
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
          export_environment_variables: true
          create_credentials_file: true
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - name: Cache sample slide
        id: cache-slide
        uses: actions/cache@v3
        with:
          path: tests/data/
          key: slides-test
      - name: Download sample tests data
        if: steps.cache-slide.outputs.cache-hit != 'true'
        run: make dl-test-images
      - name: Install dependencies
        run: make install-deps
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_VERSION }}
      - name: Install llvm-cov & Build & Tests
        run: |
          rustup component add llvm-tools-preview
          cargo install cargo-llvm-cov
          cargo llvm-cov clean --workspace # remove artifacts that may affect the coverage results
          cargo llvm-cov --no-report --workspace
          cargo llvm-cov --no-run --workspace --lcov --output-path lcov.info
      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
          name: codecov-philips-isyntax-rs # optional
          verbose: true # optional (default = false)
