name: Coverage

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  coverage:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Google Storage authentication
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
          export_environment_variables: true
          create_credentials_file: true
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      - name: Install dependencies
        run: make install-deps
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install llvm-cov & Build & Tests
        run: |
          rustup component add llvm-tools-preview
          cargo install cargo-llvm-cov
          cargo llvm-cov clean --workspace # remove artifacts that may affect the coverage results
          cargo llvm-cov --no-report --workspace
          cargo llvm-cov --no-run --workspace --lcov --output-path lcov.info
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
          name: codecov-philips-isyntax-rs # optional
          verbose: true # optional (default = false)
