name: Build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
        fail-fast: false
        matrix:
          os: [ "ubuntu-20.04" ]
          feature: [ "--no-default-features", "" ]

    steps:
    - uses: actions/checkout@v3
    - name: Google Storage authentication
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
        export_environment_variables: true
        create_credentials_file: true
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: Cache sample slide
      id: cache-slide
      uses: actions/cache@v3
      with:
        path: tests/data/
        key: slides-test
    - name: Download sample tests data
      if: steps.cache-slide.outputs.cache-hit != 'true'
      run: make dl-test-images
    - uses: Swatinem/rust-cache@v2
      with:
        key: ${{ matrix.os }}-${{ matrix.feature }}
    - name: Install dependencies ubuntu
      run: make install-deps
    - name: Build & Test
      run: cargo test --workspace ${{ matrix.feature }} -- --nocapture --test-threads=1

  doc-rs:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - name: Generate Doc
      env:
        DOCS_RS: 1
      run: cargo doc -v

  pre-commit:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: clippy, rustfmt
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install pre-commit
      run: pip install pre-commit
    - name: Pre-commit
      run: |
        pre-commit install --install-hooks
        pre-commit run --all --show-diff-on-failure
